import type { Metadata } from "next";

import Header from "@root/components/layout/Header";
import Footer from "@root/components/layout/Footer";

import "@root/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-black bg-site">
        <Header />

        <main className="bg-site min-h-[600px]">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
