import type { Metadata } from "next";

import Header from "@root/app/components/layout/Header";

import "./globals.css";
import Footer from "./components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-black bg-site">
        <Header />
        <main className="bg-site min-h-[600px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
